-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-17 00:04:52 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE castle (
    castle_name VARCHAR2(26 BYTE) NOT NULL
);

ALTER TABLE castle ADD CONSTRAINT castle_pk PRIMARY KEY ( castle_name );

CREATE TABLE fav_unit (
    user_name  VARCHAR2(26 BYTE) NOT NULL,
    unit_name  VARCHAR2(26 BYTE) NOT NULL
);

ALTER TABLE fav_unit ADD CONSTRAINT fav_unit_pk PRIMARY KEY ( user_name,
                                                              unit_name );

CREATE TABLE properties (
    property_name VARCHAR2(26 BYTE) NOT NULL
);

ALTER TABLE properties ADD CONSTRAINT properties_pk PRIMARY KEY ( property_name );

CREATE TABLE unit (
    unit_name VARCHAR2(26 BYTE) NOT NULL
);

ALTER TABLE unit ADD CONSTRAINT unit_pk PRIMARY KEY ( unit_name );

CREATE TABLE unit_castle (
    unit_name    VARCHAR2(26 BYTE) NOT NULL,
    castle_name  VARCHAR2(26 BYTE) NOT NULL
);

ALTER TABLE unit_castle ADD CONSTRAINT unit_castle_pk PRIMARY KEY ( unit_name );

CREATE TABLE unit_property (
    unit_name       VARCHAR2(26 BYTE) NOT NULL,
    property_name   VARCHAR2(26 BYTE) NOT NULL,
    property_value  VARCHAR2(26 BYTE)
);

ALTER TABLE unit_property ADD CONSTRAINT unit_property_pk PRIMARY KEY ( unit_name,
                                                                        property_name );

CREATE TABLE "USER" (
    user_name VARCHAR2(26 BYTE) NOT NULL
);

ALTER TABLE "USER" ADD CONSTRAINT user_pk PRIMARY KEY ( user_name );

ALTER TABLE fav_unit
    ADD CONSTRAINT fav_unit_unit_fk FOREIGN KEY ( unit_name )
        REFERENCES unit ( unit_name );

ALTER TABLE fav_unit
    ADD CONSTRAINT fav_unit_user_fk FOREIGN KEY ( user_name )
        REFERENCES "USER" ( user_name );

ALTER TABLE unit_castle
    ADD CONSTRAINT unit_castle_fk FOREIGN KEY ( castle_name )
        REFERENCES castle ( castle_name );

ALTER TABLE unit_castle
    ADD CONSTRAINT unit_castle_unit_fk FOREIGN KEY ( unit_name )
        REFERENCES unit ( unit_name );

ALTER TABLE unit_property
    ADD CONSTRAINT unit_property_properties_fk FOREIGN KEY ( property_name )
        REFERENCES properties ( property_name );

ALTER TABLE unit_property
    ADD CONSTRAINT unit_property_unit_fk FOREIGN KEY ( unit_name )
        REFERENCES unit ( unit_name );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             13
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0