CREATE TYPE HERO_ROW_TYPE AS OBJECT(
    USER_NAME VARCHAR2 (26 BYTE),
    UNIT_NAME VARCHAR2 (26 BYTE),
    CASTLE VARCHAR2 (26 BYTE),
    GOLD VARCHAR2 (26 BYTE)
);
    
CREATE TYPE HERO_TABLE_PARAMS_TYPE is TABLE of HERO_ROW_TYPE;

CREATE OR REPLACE FUNCTION HERO_INFO(MIN_PRICE INT DEFAULT 0, USER1 VARCHAR2 DEFAULT 'Bob')
RETURN HERO_TABLE_PARAMS_TYPE
PIPELINED
IS
BEGIN  
    FOR HERO_ITERATOR IN (
    SELECT FAV_UNIT.USER_NAME, UNIT_PROPERTY.UNIT_NAME, UNIT_CASTLE.CASTLE_NAME, PROPERTY_VALUE AS GOLD
    FROM UNIT_PROPERTY JOIN UNIT_CASTLE ON UNIT_PROPERTY.UNIT_NAME = UNIT_CASTLE.UNIT_NAME
    JOIN FAV_UNIT ON FAV_UNIT.UNIT_NAME = UNIT_CASTLE.UNIT_NAME
    WHERE PROPERTY_NAME = 'Gold' AND PROPERTY_VALUE > MIN_PRICE AND USER_NAME = USER1
    )
    LOOP
        PIPE ROW(HERO_ITERATOR);
    END LOOP;
END;
