CREATE OR REPLACE PACKAGE HEROES_PKG is

    TYPE HERO_ROW_TYPE is RECORD(
        USER_NAME FAV_UNIT.USER_NAME%TYPE,
        UNIT_NAME UNIT_PROPERTY.UNIT_NAME%TYPE,
        CASTLE UNIT_CASTLE.CASTLE_NAME%TYPE,
        GOLD UNIT_PROPERTY.PROPERTY_VALUE%TYPE
    );
    
    TYPE HERO_TABLE_PARAMS_TYPE is TABLE of HERO_ROW_TYPE;
    
    
    FUNCTION HERO_INFO(MIN_PRICE INT DEFAULT 0, USER1 VARCHAR2 DEFAULT 'Bob')
    RETURN HERO_TABLE_PARAMS_TYPE
    PIPELINED; 
    
    PROCEDURE DELETE_UNIT (USER_NAME_IN IN FAV_UNIT.USER_NAME%TYPE, UNIT_NAME_IN IN FAV_UNIT.UNIT_NAME%TYPE);


END HEROES_PKG;
/
CREATE OR REPLACE PACKAGE BODY HEROES_PKG is

        FUNCTION HERO_INFO(MIN_PRICE INT DEFAULT 0, USER1 VARCHAR2 DEFAULT 'Bob')
        RETURN HERO_TABLE_PARAMS_TYPE
        PIPELINED
        IS
        BEGIN
        
            FOR HERO_ITERATOR IN (
                    SELECT FAV_UNIT.USER_NAME, UNIT_PROPERTY.UNIT_NAME, CASTLE_NAME, PROPERTY_VALUE AS GOLD
                    FROM UNIT_PROPERTY JOIN UNIT_CASTLE ON UNIT_PROPERTY.UNIT_NAME = UNIT_CASTLE.UNIT_NAME
                    JOIN FAV_UNIT ON FAV_UNIT.UNIT_NAME = UNIT_CASTLE.UNIT_NAME
                    WHERE PROPERTY_NAME = 'Gold' AND PROPERTY_VALUE > MIN_PRICE AND USER_NAME = USER1
                    )
            LOOP
                PIPE ROW(HERO_ITERATOR);
            END LOOP;
            
        END;
        
        PROCEDURE DELETE_UNIT (USER_NAME_IN IN FAV_UNIT.USER_NAME%TYPE, UNIT_NAME_IN IN FAV_UNIT.UNIT_NAME%TYPE)
        IS
            ROWAMOUNT INT := 0;
            ROW_EXCEPTION EXCEPTION;
        BEGIN
            SELECT COUNT(*) INTO ROWAMOUNT FROM FAV_UNIT
            WHERE USER_NAME = USER_NAME_IN AND UNIT_NAME = UNIT_NAME_IN;
            IF ROWAMOUNT = 0 THEN
                RAISE ROW_EXCEPTION;
            END IF;
            DELETE FROM FAV_UNIT
            WHERE USER_NAME = USER_NAME_IN AND UNIT_NAME = UNIT_NAME_IN;
        EXCEPTION
            WHEN ROW_EXCEPTION
            THEN DBMS_OUTPUT.PUT_LINE('Oh shit, dopka is coming');
            WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Something else went wrong - ' || SQLCODE ||' : ' || SQLERRM);
        END;


END HEROES_PKG;


        
