CREATE OR REPLACE PROCEDURE DELETE_UNIT (USER_NAME_IN IN FAV_UNIT.USER_NAME%TYPE, UNIT_NAME_IN IN FAV_UNIT.UNIT_NAME%TYPE)
IS
    ROWAMOUNT INT := 0;
    ROW_EXCEPTION EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO ROWAMOUNT FROM FAV_UNIT
    WHERE USER_NAME = USER_NAME_IN AND UNIT_NAME = UNIT_NAME_IN;
    IF ROWAMOUNT = 0 THEN
        RAISE ROW_EXCEPTION;
    END IF;
    DELETE FROM FAV_UNIT
    WHERE USER_NAME = USER_NAME_IN AND UNIT_NAME = UNIT_NAME_IN;
EXCEPTION
    WHEN ROW_EXCEPTION
    THEN DBMS_OUTPUT.PUT_LINE('Wrong data');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Something else went wrong - ' || SQLCODE ||' : ' || SQLERRM);
END;